source 'https://rubygems.org'

gem 'font-awesome-sass'
gem 'koala', '~> 2.0'
gem 'paperclip', '~> 4.3'
gem 'aasm'
gem 'annotate'
gem 'aws-sdk'
gem 'bootstrap-sass'
gem 'byebug'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'dotenv-rails', :groups => [:development, :test]
gem 'geocoder'
gem 'google-api-client'
gem 'haml-rails'
gem 'heroku-deflater', :group => :production
gem 'html2haml'
gem 'httparty'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'newrelic_rpm',:group => :production
gem 'nexmo'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'parse-ruby-client'
gem 'pg'
gem 'puma'
gem 'pusher'
gem 'rack-mini-profiler'
gem 'rails', '4.1.8'
gem 'rails_12factor', group: :production
gem 'rolify'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'social-share-button'
gem 'spring',        group: :development
gem 'turbolinks'
gem 'typhoeus'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.0.6'
gem 'image_optim'
gem 'image_optim_pack'
gem 'paperclip-optimizer'
gem 'delayed_job_active_record'