source 'https://rubygems.org'

gem 'font-awesome-sass'
gem 'koala', '~> 2.0'
gem 'paperclip', '~> 4.3'
gem 'aasm'
gem 'aws-sdk'
gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.0.0'
gem 'daemons'
gem 'devise'
gem 'dotenv-rails', :groups => [:development, :test]
gem 'geocoder'
gem 'google-api-client'
gem 'haml-rails'
gem 'heroku-deflater', :group => :production
gem 'httparty'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'newrelic_rpm',:group => :production
gem 'nexmo'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'parse-ruby-client'
gem 'pg'
gem 'puma'
gem 'pusher'
gem 'rails', '4.1.8'
gem 'rails_12factor', group: :production
gem 'rolify'
gem 'roadie-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'turbolinks'
gem 'typhoeus'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.0.6'
gem 'delayed_job_active_record'
gem 'devise-two-factor'
gem 'rotp'
gem 'border_patrol'
gem 'sitemap_generator'
gem 'fog-aws'
gem 'fog'
gem 'airbrake'
gem 'mixpanel-ruby'
gem "figaro"
gem 'metamagic'
gem 'cloudinary'
gem 'telerivet'

group :development do
  gem "bullet"
  gem 'derailed'
  gem 'stackprof'
  gem 'spring'
  gem 'rack-mini-profiler'
  gem 'html2haml'
  gem 'byebug'
  gem 'annotate'
end